### ISSUE TITLE
Licence of code

### ISSUE THREAD

**Issue by dmlr1996** [alsiola/DeclarativeConsoleMenu#1]
Hi @alsiola,
thanks a lot for the creation of the code. Its very useful and helps pretty much for nice menu structures.

There is no licence included in your repo and I would like to fork your repo or add a new fuction. Could xou please tell me, what kind of licence you want to use for your code?

Best regards
~dmlr

**Comment by alsiola** [comment]
Hey @dmlr1996 - it's a long time since I did any work in this repo, or on C# in general to be honest. If there are changes you would like to make then forking is probably the best way forward, because I won't be able to make any sensible judgement on whether to merge PRs etc.

I'll add a licence to the repo, something as permissive as I can find.
